### ISSUE TITLE
Investigate RIST over SRT

### ISSUE THREAD

**Issue by shleeable** [BELABOX/belacoder#1]
hey hey, I've used SRT, but RIST is advertised as designed for BELABOX style streaming.

"We strive to make the world adopt an interoperable standard, Reliable Internet Stream Transport (RIST), for transporting live video over unmanaged networks. "

details: https://www.rist.tv/
code: https://code.videolan.org/rist

one pager: https://www.videoservicesforum.org/activity_groups/RIST_poster_for_VidTrans2018Feb25.pdf

**Comment by shleeable** [comment]
RIST seems to support bonding out of the box.. these details are from the wikipedia
```
RIST Simple Profile[3] was published in October 2018 and includes the following features:

    The base stream uses RTP for compatibility with existing equipment.
    Retransmission requests use RTCP. Two types of retransmission requests are defined:
        A Bitmask NACK, defined in RFC 4585.
        A Range NACK, defined as an APP RTCP packet.
    **Bonding of multiple links for load sharing.**
    Seamless switching using SMPTE-2022-7.
    Out-of-band transmission of protection data.

The RIST AG is working on an update to RIST Simple Profile that adds link probing to allow for dynamic ARQ protection. 
```

SRT can recover from packet loss up to range of 15%. The RIST Forum advertises resilience for up to 50 % packet loss (editor's note (pkv@obsproject): I did test successfully a transatlantic rist stream from Paris, France to Florida, with obs; it worked in spite of the 50% packet loss I simulated through a network testing app).

- https://obsproject.com/wiki/Streaming-With-SRT-Or-RIST-Protocols

**Comment by rationalsa** [comment]
Already did. No suitable bonding with dynamic load sharing. Packet loss is minimal over mobile networks. Packet loss resilience needs to exist, but its performance is far from being the main selection criterion. Also, SRT can work fine with higher packet loss than 15%, it just depends on how you set it up.
