### ISSUE TITLE
Question about using this project on raspberry pi 4b

### ISSUE THREAD

**Issue by FovenX3** [BELABOX/belacoder#2]
I successfully compile belacoder on my rpi4b, but the raspberry pi use v4l2h264enc for hardware encode. The bitrate option is hide under `v4l2h264enc extra-controls="controls,h264_profile=16,h264_level=15,video_bitrate=10000000;" ` do I need to slightly modify the program enorder to work on rpi?
Thanks!

**Comment by rationalsa** [comment]
We only support Jetson Nano. RPis have a very low quality H264 hardware encoder and the Arm cores are too slow to get good quality out of software encoding, it's not worth the bother to support them.
