### ISSUE TITLE
porting Belabox to VIM4?

### ISSUE THREAD

**Issue by chilledsheep** [BELABOX/belacoder#5]
today i found the Khadas VIM4 SBC which features onboard HDMI Input, 4k/50p h264/h265 encoder, Mali G52 GPU and M2 slot for connecting 4G/5G Modem.

sounds like a better platform for belabox because the jetson nano is almost nowhere available anymore and if it is then prices are at around 300$.

are you interested in porting belabox to VIM4?

**Comment by rationalsa** [comment]
Won't port to Amlogic A311D2, but you may be interested in the RK3588 port https://belabox.net/rk3588/
